Q1. Create two 3×3 matrices using the random function in Numpy and perform the following operations.

    1.Product (prod)
    2.Multiplication (multiply)
    3.Dot Product (dot)

In [1]:
import numpy as np
arr1=np.random.randint(1,5,(3,3))
arr2=np.random.randint(1,6,(3,3))
print("Array1 : \n",arr1)
print("Array2 : \n",arr2)
print("Multiply : \n",np.multiply(arr1,arr2))
print("Product : \n",np.prod([arr1,arr2]))
print("Dot : \n",np.dot(arr1,arr2))

Array1 : 
 [[4 2 1]
 [4 3 2]
 [3 2 2]]
Array2 : 
 [[2 3 5]
 [4 3 3]
 [3 4 2]]
Multiply : 
 [[ 8  6  5]
 [16  9  6]
 [ 9  8  4]]
Product : 
 59719680
Dot : 
 [[19 22 28]
 [26 29 33]
 [20 23 25]]


Q2. Perform the following set operations using the Numpy functions.

    1.Union
    2.Intersection
    3.Set difference
    4.XOR

In [2]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([3,4,5,6])
print("Union : ",np.union1d(arr1,arr2))

print("Intersection : ",np.intersect1d(arr1,arr2))

print("Set Difference : ",np.setdiff1d(arr1,arr2))

print("XOR : ",np.setxor1d(arr1,arr2))

Union :  [1 2 3 4 5 6]
Intersection :  [3 4]
Set Difference :  [1 2]
XOR :  [1 2 5 6]


Q3. Create a 1D array using Random function and perform the following operations.

    Cumulative sum
    Cumulative Product
    Discrete difference (with n=3)
    Find the unique elements from the array

In [4]:
import numpy as np
arr1=np.random.randint(10 ,size=10)
print(arr1)
print("Cumulative sum : ",np.cumsum(arr1))
print("Cumulative Product : ",np.cumprod(arr1))
print("Discrete difference (with n=3) : ",np.diff(arr1, n=3))
print("The unique elements from the array : ",np.unique(arr1))

[9 6 6 2 6 6 3 6 5 9]
Cumulative sum :  [ 9 15 21 23 29 35 38 44 49 58]
Cumulative Product :  [       9       54      324      648     3888    23328    69984   419904
  2099520 18895680]
Discrete difference (with n=3) :  [ -7  12 -12   1   9 -10   9]
The unique elements from the array :  [2 3 5 6 9]


Q4. Create two 1D array and perform the Addition using zip(), add() and user defined function (frompyfunc())

In [6]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([3,4,5,6])
z=[]
#print(zip(arr1,arr2))
for i,j in zip(arr1,arr2):
    z.append(i+j)
print(z)

print(np.add(arr1,arr2))

def adds(x,y):
    return x+y
print(adds(arr1,arr2))
result=np.frompyfunc(adds,2,1)
print(result(4,5))

[4, 6, 8, 10]
[ 4  6  8 10]
[ 4  6  8 10]
9


Q5. Find the LCM (Least Common Multiple) and GCD (Greatest Common Divisor) of an array of elements using reduce().

In [14]:
import numpy as np
arr1=np.array([[[20,70]],[[40,80]]])
arr2=np.array([20,40])
print("LCM : ",np.lcm.reduce(arr1))
print("GCD : ",np.gcd.reduce(arr2))

LCM :  [[ 40 560]]
GCD :  20
